version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
        - "Cyb3r-Jak3"
    labels:
        - "dependencies"
    reviewers:
        - "Cyb3r-Jak3"
    commit-message:
      prefix: "Docker Update"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
        - "Cyb3r-Jak3"
    labels:
        - "dependencies"
    reviewers:
        - "Cyb3r-Jak3"
    commit-message:
      prefix: "Action Update"

  - package-ecosystem: "pip"
    directory: "/"
    labels:
        - "dependencies"
    schedule:
      interval: "daily"
    assignees:
      - "Cyb3r-Jak3"
    commit-message:
      prefix: "Pip Update"
    reviewers:
      - "Cyb3r-Jak3"