name: Docker

on:
  push:


jobs:
  Slim:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker
      uses: docker/login-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login To GitHub
      uses: docker/login-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Login To GitLab
      uses: docker/login-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USER }}
        password: ${{ secrets.GITLAB_TOKEN }}

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: cyb3rjak3/pypy-flask,ghcr.io/cyb3r-jak3/pypy-flask,registry.gitlab.com/cyb3r-jak3/pypy-flask
        tags: |
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/pypy-flask.git
          org.label-schema.schema-version=1.0.0-rc1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Cache Docker layers
      uses: actions/cache@v2.1.5
      with:
        path: /tmp/.buildx-cache
        key: buildx-slim-${{ github.sha }}
        restore-keys: buildx-slim

    - name: Slim Build and Push
      uses: docker/build-push-action@v2.4.0
      with:
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        file: Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  Alpine:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to Docker
      uses: docker/login-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login To GitHub
      uses: docker/login-action@v1 
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Login To GitLab
      uses: docker/login-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USER }}
        password: ${{ secrets.GITLAB_TOKEN }}

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: cyb3rjak3/pypy-flask,ghcr.io/cyb3r-jak3/pypy-flask,registry.gitlab.com/cyb3r-jak3/pypy-flask
        flavor: |
          suffix=-alpine
        tags: |
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/pypy-flask.git
          org.label-schema.schema-version=1.0.0-rc1

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Cache Docker layers
      uses: actions/cache@v2.1.5
      with:
        path: /tmp/.buildx-cache
        key: buildx-alpine-${{ github.sha }}
        restore-keys: buildx-alpine

    - name: Alpine Build and Push
      uses: docker/build-push-action@v2.4.0
      with:
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        file: alpine.Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}