name: Docker

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
    paths:
      - .github/workflows/docker.yml
      - '*.Dockerfile'
      - requirements.txt
      - docker-bake.hcl


jobs:
  Bake:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        bake-target: ["alpine", "slim"]
        flask: ${{fromJSON(steps.set-matrix.outputs.matrix).flask}}
        gunicorn: ${{fromJSON(steps.set-matrix.outputs.matrix).gunicorn}}
        gevent: ${{fromJSON(steps.set-matrix.outputs.matrix).gevent}}
    steps:
    - name: Load JSON to matrix
      id: set-matrix
      run:
        output=$(cat ./versions)
        output="${output//'%'/'%25'}"
        output="${output//$'\n'/'%0A'}"
        output="${output//$'\r'/'%0D'}"
        echo "::set-output name=matrix::$content"
    - name: Login to Docker
      uses: docker/login-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Login To GitHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Login To GitLab
      uses: docker/login-action@v1
      if: ${{ startsWith(github.ref, 'refs/tags/v') }}
      with:
        registry: registry.gitlab.com
        username: ${{ secrets.GITLAB_USER }}
        password: ${{ secrets.GITLAB_TOKEN }}

    - name: Docker Meta
      id: meta
      uses: docker/metadata-action@v3.5.0
      with:
        images: cyb3rjak3/pypy-flask,ghcr.io/cyb3r-jak3/pypy-flask,registry.gitlab.com/cyb3r-jak3/pypy-flask
        tags: |
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=sha
        labels: |
          org.label-schema.vcs-url=https://github.com/Cyb3r-Jak3/pypy-flask.git
          org.label-schema.schema-version=1.0.0-rc1
          maintainer=Cyb3r Jak3 jake@jwhite.network
          org.opencontainers.image.vendor=cyb3rjak3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.5.1

    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      uses: docker/bake-action@v1.5.0
      with:
        files: |
          ./docker-bake.hcl
          ${{ steps.meta.outputs.bake-file }}
        targets: ${{ matrix.bake-target }}-release
        push: ${{ startsWith(github.ref, 'refs/tags/v') }}
        pull: true