name: Docker

on:
  push:


jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:

    - name: Login to Docker
      run: echo ${{ secrets.DOCKER_PASSWORD }} |  docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Login To GitHub
      run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Login To GitLab
      run: echo ${{ secrets.GITLAB_TOKEN }} | docker login registry.gitlab.com -u ${{ secrets.GITLAB_USER }} --password-stdin

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.3.0

    - name: Cache Docker layers
      uses: actions/cache@v2.1.5
      with:
        path: /tmp/.buildx-cache
        key: buildx-${{ github.sha }}
        restore-keys: buildx

    - name: Build and Push
      uses: docker/build-push-action@v2.4.0
      with:
        platforms: linux/amd64,linux/arm64
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
        push: ${{ github.ref == 'refs/heads/main' }}
        file: Dockerfile
        tags: |
          cyb3rjak3/pypy-flask:latest
          ghcr.io/cyb3r-jak3/pypy-flask:latest
          registry.gitlab.com/cyb3r-jak3/pypy-flask:latest